apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/gke-teste/java11-builder:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/gke-teste/java11-builder:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: java11-builder
        chartPath: charts/java11-builder
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/gke-teste/java11-builder'
          image.tag: '{{.DIGEST_HEX}}'
